@startuml

class RuntimeException

abstract class BeansException

class BeanDefinitionStoreException

class BeanCreationException


BeansException --|> RuntimeException
BeanCreationException --|> BeansException
BeanDefinitionStoreException --|> BeansException
@enduml
